title: "echoIA Community"
tagline: "Intrinsic Alignments, end-to-end."

owner: "echoIA Community"

site_content_license_name: "CC BY 4.0"
site_content_license_url: "https://creativecommons.org/licenses/by/4.0/"
metadata_license_name: "CC0 1.0"
metadata_license_url: "https://creativecommons.org/publicdomain/zero/1.0/"
code_license_name: "MIT"
code_license_url: "https://opensource.org/license/mit"

zenodo_community_url: "https://zenodo.org/communities/echo-ia"

url: "https://echoia.org"
baseurl: ""
permalink: pretty

defaults:
  - scope:
      path: "pages"
      type: "pages"
    values:
      permalink: "/:basename/"
      layout: page
      show_banner: true

plugins:
  - jekyll-github-metadata
repository: echo-ia/echoia-hub
exclude: [vendor]

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
